name       : kwayland-server
version    : 5.20.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.1/kwayland-server-5.20.1.tar.xz : afdadebf8ab32c5598ff7e3bb60d1c37920c639c122a27874a38453a33287d02
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Wayland server components built on KDE Frameworks
description: |
    Wayland server components built on KDE Frameworks
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kwayland-devel
    - plasma-wayland-protocols-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
