name       : kwayland-server
version    : 5.24.4
release    : 29
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.4/kwayland-server-5.24.4.tar.xz : d1790bd7584dce9a36a432819b170ce72d34d5df79083b1b41dfe3e021b6e988
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Wayland server components built on KDE Frameworks
description: |
    Wayland server components built on KDE Frameworks
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - kwayland-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - devel :
        - kwayland-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
