name       : kwayland-server
version    : 5.22.5
release    : 20
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.5/kwayland-server-5.22.5.tar.xz : dd64bdd629b239621d687d8deceff6e0da88542c6b67140c5ff8b654155bf39d
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Wayland server components built on KDE Frameworks
description: |
    Wayland server components built on KDE Frameworks
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - kwayland-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - devel :
        - kwayland-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
