name       : kwayland-server
version    : 5.21.4
release    : 15
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.4/kwayland-server-5.21.4.tar.xz : ff32f4e6b92fc900db41780cb2f2645c472e6ec5d3999aa17fb0fba807df71d6
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Wayland server components built on KDE Frameworks
description: |
    Wayland server components built on KDE Frameworks
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - kwayland-devel
    - plasma-wayland-protocols-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
