name       : kwayland-server
version    : 5.23.1
release    : 22
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.1/kwayland-server-5.23.1.tar.xz : ebad1a6dc1bf246cab9ca8ba0a13edd578646cb333ce09303d79d78727a59d57
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Wayland server components built on KDE Frameworks
description: |
    Wayland server components built on KDE Frameworks
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - kwayland-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - devel :
        - kwayland-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
